config/routes.rb
Rails.application.routes.draw do
  resources :attachments
  resources :essay_solutions
  resources :essays
  resources :lessons
  resources :resources
  resources :users_courses
  resources :courses
  resources :schools
  # get 'home/index'
  root 'home#index'
  get 'home/about'
  get 'users/adding/adding_manually'
  get 'users/adding/save_users'
  get 'home/show_users'
  get 'users/adding/import_users'
  get 'users/adding/adding_csv'
  devise_for :users, controllers: { sessions: 'users/sessions' , registrations: 'users/registrations'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
end

app/models/course.rb
class Course < ApplicationRecord
    has_and_belongs_to_many :users
end

app/models/essay.rb
class Essay < ApplicationRecord
end

app/models/essay_solution.rb
class EssaySolution < ApplicationRecord
end

app/models/lesson.rb
class Lesson < ApplicationRecord
end

app/models/resource.rb
class Resource < ApplicationRecord
end

app/models/school.rb
class School < ApplicationRecord
    has_many :users,  inverse_of: :school, dependent: :destroy 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
  belongs_to :school, foreign_key: :school_id
  has_and_belongs_to_many :courses

  accepts_nested_attributes_for :school, reject_if: ->(attributes){ attributes['name'].blank? || attributes['subdomain'].blank? }, allow_destroy: true

  def with_school
    build_school if school.nil?
    self
  end
end

app/models/users_course.rb
class UsersCourse < ApplicationRecord
end

app/controllers/essay_solutions_controller.rb
class EssaySolutionsController < ApplicationController
  before_action :set_essay_solution, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /essay_solutions or /essay_solutions.json
  def index
    @essay_solutions = EssaySolution.all
  end

  # GET /essay_solutions/1 or /essay_solutions/1.json
  def show
  end

  # GET /essay_solutions/new
  def new
    @essay_solution = EssaySolution.new
  end

  # GET /essay_solutions/1/edit
  def edit
  end

  # POST /essay_solutions or /essay_solutions.json
  def create
    @essay_solution = EssaySolution.new(essay_solution_params)

    respond_to do |format|
      if @essay_solution.save
        format.html { redirect_to @essay_solution, notice: "Essay solution was successfully created." }
        format.json { render :show, status: :created, location: @essay_solution }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @essay_solution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /essay_solutions/1 or /essay_solutions/1.json
  def update
    respond_to do |format|
      if @essay_solution.update(essay_solution_params)
        format.html { redirect_to @essay_solution, notice: "Essay solution was successfully updated." }
        format.json { render :show, status: :ok, location: @essay_solution }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @essay_solution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /essay_solutions/1 or /essay_solutions/1.json
  def destroy
    @essay_solution.destroy
    respond_to do |format|
      format.html { redirect_to essay_solutions_url, notice: "Essay solution was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_essay_solution
      @essay_solution = EssaySolution.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def essay_solution_params
      params.require(:essay_solution).permit(:essay_id, :student_id, :solution, :attachment)
    end
end

app/controllers/essays_controller.rb
class EssaysController < ApplicationController
  before_action :set_essay, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /essays or /essays.json
  def index
    @essays = Essay.all
  end

  # GET /essays/1 or /essays/1.json
  def show
  end

  # GET /essays/new
  def new
    @essay = Essay.new
  end

  # GET /essays/1/edit
  def edit
  end

  # POST /essays or /essays.json
  def create
    @essay = Essay.new(essay_params)

    respond_to do |format|
      if @essay.save
        format.html { redirect_to @essay, notice: "Essay was successfully created." }
        format.json { render :show, status: :created, location: @essay }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @essay.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /essays/1 or /essays/1.json
  def update
    respond_to do |format|
      if @essay.update(essay_params)
        format.html { redirect_to @essay, notice: "Essay was successfully updated." }
        format.json { render :show, status: :ok, location: @essay }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @essay.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /essays/1 or /essays/1.json
  def destroy
    @essay.destroy
    respond_to do |format|
      format.html { redirect_to essays_url, notice: "Essay was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_essay
      @essay = Essay.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def essay_params
      params.require(:essay).permit(:name, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def show_users
    @users = User.where(:school_id => current_user.school_id)
    puts @users.inspect
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def resource_name
        :user
    end

    def resource
        @resource ||= User.new
    end

    def devise_mapping
        @devise_mapping ||= Devise.mappings[:user]
    end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/essay_solutions_helper.rb
module EssaySolutionsHelper
end

app/helpers/essays_helper.rb
module EssaysHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/users_courses_helper.rb
module UsersCoursesHelper
end

app/views/essay_solutions/_form.html.erb
<%= form_with(model: essay_solution) do |form| %>
  <% if essay_solution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(essay_solution.errors.count, "error") %> prohibited this essay_solution from being saved:</h2>

      <ul>
        <% essay_solution.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :essay_id %>
    <%= form.number_field :essay_id %>
  </div>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.number_field :student_id %>
  </div>

  <div class="field">
    <%= form.label :solution %>
    <%= form.text_area :solution %>
  </div>

  <div>
    <button class="btn btn-primary" type="button" onclick="files(event)">Upload Solution</button>
    <%= form.hidden_field :attachment, id:"hidden_input_files" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script type="text/javascript">
  function files(event){
    event.preventDefault();
    filepicker.setKey('AEgoy56fEQziKJ8ajM2Luz');

    filepicker.pickMultiple(
      {
        maxFiles: 3
      },
      function(Blobs){
        var my_blobs = [];
        for(var i = 0; i < Blobs.length; i++){
          my_blobs.push(Blobs[i].url);
          $("#hidden_input_files").val(my_blobs);
          $( "#my_form" ).append( '<p><span class="glyphicon glyphicon-file"></span><b>' + Blobs[i].filename + '</b></p>'  );
        }
      },
      function(error){}
    );
  }
</script>

app/views/essay_solutions/edit.html.erb
<div class="content-container">
    <div class="container-fluid"> 

        <h1>Editing Essay Solution</h1>

        <%= render 'form', essay_solution: @essay_solution %>

        <%= link_to 'Show', @essay_solution %> |
        <%= link_to 'Back', essay_solutions_path %>

    </div>
</div>

app/views/essay_solutions/index.html.erb
<div class="content-container">
  <div class="container-fluid"> 

    <h1>Essay Solutions</h1>

    <table>
      <thead>
        <tr>
          <th>Essay</th>
          <th>Student</th>
          <th>Solution</th>
          <th>Attachment</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @essay_solutions.each do |essay_solution| %>
          <tr>
            <td><%= essay_solution.essay_id %></td>
            <td><%= essay_solution.student_id %></td>
            <td><%= essay_solution.solution %></td>
            <td><%= essay_solution.attachment %></td>
            <td><%= link_to 'Show', essay_solution %></td>
            <td><%= link_to 'Edit', edit_essay_solution_path(essay_solution) %></td>
            <td><%= link_to 'Destroy', essay_solution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Essay Solution', new_essay_solution_path %>

  </div>
</div>

app/views/essay_solutions/new.html.erb
<div class="content-container">
    <div class="container-fluid"> 

        <h1>New Essay Solution</h1>

        <%= render 'form', essay_solution: @essay_solution %>

        <%= link_to 'Back', essay_solutions_path %>

    </div>
</div>

app/views/essay_solutions/show.html.erb
<div class="content-container">
  <div class="container-fluid"> 

    <p>
      <strong>Essay:</strong>
      <%= @essay_solution.essay_id %>
    </p>

    <p>
      <strong>Student:</strong>
      <%= @essay_solution.student_id %>
    </p>

    <p>
      <strong>Solution:</strong>
      <%= @essay_solution.solution %>
    </p>

    <p>
      <strong>Attachment:</strong>
      <%= @essay_solution.attachment %>
    </p>

    <%= link_to 'Edit', edit_essay_solution_path(@essay_solution) %> |
    <%= link_to 'Back', essay_solutions_path %>

  </div>
</div>

<script type="text/javascript">
  function get_metadata(url){
    $.get( url + "/metadata", function( data ){
      get_file(data.filename,data.mimetype,data.isWriteable,data.size,url);
    });
  }

  function get_file(filename, mimetype, isWriteable, size, url){
    filepicker.setKey("AEgoy56fEQziKJ8ajM2Luz");
    var blob = {
      url: url,
      filename: filename,
      mimetype: mimetype,
      isWriteable: isWriteable,
      size: size
    };  

    filepicker.exportFile(
      blob,
      function(Blob){
        console.log(Blob.url);
      }
    );
  }
</script>