config/routes.rb
Rails.application.routes.draw do
  resources :attachments
  resources :essay_solutions
  resources :essays
  resources :lessons
  resources :resources
  resources :users_courses
  resources :courses
  resources :schools
  # get 'home/index'
  root 'home#index'
  get 'home/about'
  get 'users/adding/adding_manually'
  get 'users/adding/save_users'
  get 'home/show_users'
  get 'users/adding/import_users'
  get 'users/adding/adding_csv'
  devise_for :users, controllers: { sessions: 'users/sessions' , registrations: 'users/registrations'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
end

app/models/course.rb
class Course < ApplicationRecord
    has_and_belongs_to_many :users
end

app/models/essay.rb
class Essay < ApplicationRecord
end

app/models/essay_solution.rb
class EssaySolution < ApplicationRecord
end

app/models/lesson.rb
class Lesson < ApplicationRecord
end

app/models/resource.rb
class Resource < ApplicationRecord
end

app/models/school.rb
class School < ApplicationRecord
    has_many :users,  inverse_of: :school, dependent: :destroy 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
  belongs_to :school, foreign_key: :school_id
  has_and_belongs_to_many :courses

  accepts_nested_attributes_for :school, reject_if: ->(attributes){ attributes['name'].blank? || attributes['subdomain'].blank? }, allow_destroy: true

  def with_school
    build_school if school.nil?
    self
  end
end

app/models/users_course.rb
class UsersCourse < ApplicationRecord
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def show_users
    @users = User.where(:school_id => current_user.school_id)
    puts @users.inspect
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def resource_name
        :user
    end

    def resource
        @resource ||= User.new
    end

    def devise_mapping
        @devise_mapping ||= Devise.mappings[:user]
    end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/essays_helper.rb
module EssaysHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/users_courses_helper.rb
module UsersCoursesHelper
end

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show col-md-3" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Learning Management System</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= filestack_js_include_tag %>
    <%= filestack_js_init_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script type="text/javascript" src="//api.filestackapi.com/filestack.js"></script>
  </head>
  <body>
    <%= render 'home/header' %>
    <% if user_signed_in? %>
      <%= render 'home/sidebar' %>
    <% end %>
    <div class="container-fluid">
      <% if notice %>
        <br/>
        <%= render 'layouts/alerts' %>
      <% end %> 
      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/resources/_form.html.erb
<%= form_with(model: resource) do |form| %>
  <% if resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
        <% resource.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.number_field :course_id %>
  </div>

  <div class="field">
    <%= form.label :lesson_id %>
    <%= form.number_field :lesson_id %>
  </div>

  <div>
    <button class="btn btn-primary" type="button" onclick="files(event)">Upload Resources</button>
    <%= form.hidden_field :url, id:"hidden_input_files" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<script type="text/javascript">
  function files(event){
    event.preventDefault();
    filepicker.setKey('AEgoy56fEQziKJ8ajM2Luz');

    filepicker.pickMultiple(
      {
        mimetype: ['image/*', 'text/*'],
        maxFiles: 3
      },
      function(Blobs){
        var my_blobs = [];
        for(var i = 0; i < Blobs.length; i++){
          my_blobs.push(Blobs[i].url);
          $("#hidden_input_files").val(my_blobs);
          $( "#my_form" ).append( '<p><span class="glyphicon glyphicon-file"></span><b>' + Blobs[i].filename + '</b></p>'  );
        }
      },
      function(error){}
    );
  }
</script>

app/views/resources/edit.html.erb
<div class="content-container">
    <div class="container-fluid"> 

        <h1>Editing Resource</h1>

        <%= render 'form', resource: @resource %>

        <%= link_to 'Show', @resource %> |
        <%= link_to 'Back', resources_path %>

    </div>
</div>

app/views/resources/index.html.erb
<div class="content-container">
  <div class="container-fluid"> 

    <h1>Resources</h1>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Url</th>
          <th>Course</th>
          <th>Lesson</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @resources.each do |resource| %>
          <tr>
            <td><%= resource.name %></td>
            <td><%= resource.url %></td>
            <td><%= resource.course_id %></td>
            <td><%= resource.lesson_id %></td>
            <td><%= link_to 'Show', resource %></td>
            <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
            <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Resource', new_resource_path %>

  </div>
</div>

app/views/resources/new.html.erb
<div class="content-container">
    <div class="container-fluid"> 

        <h1>New Resource</h1>

        <%= render 'form', resource: @resource %>

        <%= link_to 'Back', courses_path %>

    </div>
</div>

app/views/resources/show.html.erb
<div class="content-container">
  <div class="container-fluid"> 

    <p>
      <strong>Name:</strong>
      <%= @resource.name %>
    </p>

    <p>
      <strong>Url:</strong>
      <%= @resource.url %>
    </p>

    <p>
      <strong>Course:</strong>
      <%= @resource.course_id %>
    </p>

    <p>
      <strong>Lesson:</strong>
      <%= @resource.lesson_id %>
    </p>

    <%= link_to 'Edit', edit_resource_path(@resource) %> |
    <%= link_to 'Back', resources_path %>

  </div>
</div>