config/routes.rb
Rails.application.routes.draw do
  resources :attachments
  resources :essay_solutions
  resources :essays
  resources :lessons
  resources :resources
  resources :users_courses
  resources :courses
  resources :schools
  # get 'home/index'
  root 'home#index'
  get 'home/about'
  get 'users/adding/adding_manually'
  get 'users/adding/save_users'
  get 'home/show_users'
  get 'users/adding/import_users'
  get 'users/adding/adding_csv'
  devise_for :users, controllers: { sessions: 'users/sessions' , registrations: 'users/registrations'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
end

app/models/course.rb
class Course < ApplicationRecord
    has_and_belongs_to_many :users
end

app/models/essay.rb
class Essay < ApplicationRecord
end

app/models/essay_solution.rb
class EssaySolution < ApplicationRecord
end

app/models/lesson.rb
class Lesson < ApplicationRecord
end

app/models/resource.rb
class Resource < ApplicationRecord
end

app/models/school.rb
class School < ApplicationRecord
    has_many :users,  inverse_of: :school, dependent: :destroy 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
  belongs_to :school, foreign_key: :school_id
  has_and_belongs_to_many :courses

  accepts_nested_attributes_for :school, reject_if: ->(attributes){ attributes['name'].blank? || attributes['subdomain'].blank? }, allow_destroy: true

  def with_school
    build_school if school.nil?
    self
  end
end

app/models/users_course.rb
class UsersCourse < ApplicationRecord
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
    @all_resources = Resource.all
  end

  # GET /courses/new
  def new
    @courses = Course.all
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:name, :description)
    end
end

app/controllers/essays_controller.rb
class EssaysController < ApplicationController
  before_action :set_essay, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /essays or /essays.json
  def index
    @essays = Essay.all
  end

  # GET /essays/1 or /essays/1.json
  def show
  end

  # GET /essays/new
  def new
    @essay = Essay.new
  end

  # GET /essays/1/edit
  def edit
  end

  # POST /essays or /essays.json
  def create
    @essay = Essay.new(essay_params)

    respond_to do |format|
      if @essay.save
        format.html { redirect_to @essay, notice: "Essay was successfully created." }
        format.json { render :show, status: :created, location: @essay }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @essay.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /essays/1 or /essays/1.json
  def update
    respond_to do |format|
      if @essay.update(essay_params)
        format.html { redirect_to @essay, notice: "Essay was successfully updated." }
        format.json { render :show, status: :ok, location: @essay }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @essay.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /essays/1 or /essays/1.json
  def destroy
    @essay.destroy
    respond_to do |format|
      format.html { redirect_to essays_url, notice: "Essay was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_essay
      @essay = Essay.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def essay_params
      params.require(:essay).permit(:name, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def show_users
    @users = User.where(:school_id => current_user.school_id)
    puts @users.inspect
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def resource_name
        :user
    end

    def resource
        @resource ||= User.new
    end

    def devise_mapping
        @devise_mapping ||= Devise.mappings[:user]
    end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/essays_helper.rb
module EssaysHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/users_courses_helper.rb
module UsersCoursesHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<div class="content-container">
    <div class="container-fluid"> 

        <h1>Editing Course</h1>

        <%= render 'form', course: @course %>

        <%= link_to 'Show', @course %> |
        <%= link_to 'Back', courses_path %>

    </div>
</div>

app/views/courses/index.html.erb
<div class="content-container">
  <div class="container-fluid"> 

    <h1>Courses</h1>

    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <thead class="table-dark">
          <tr>
          <th> ID </th>
          <th>Name</th>
          <th>Description</th>
          <th colspan="4"></th>
          </tr>
        </thead>

        <tbody>
          <% @courses.each do |course| %>
            <tr>
            <td><%= course.id %></td>
              <td><%= course.name %></td>
              <td><%= course.description %></td>
              <td><%= link_to 'Show', course %></td>
              <td><%= link_to 'Edit', edit_course_path(course) %></td>
              <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <td><%= link_to 'Show Members', users_courses_path %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= link_to 'New Course', new_course_path, class:"btn btn-primary" %>
  
    </div>

  </div>
</div>

app/views/courses/new.html.erb
<div class="content-container">
    <div class="container-fluid"> 

        <h1>New Course</h1>

        <%= render 'form', course: @course %>

        <%= link_to 'Back', courses_path %>

    </div>
</div>

app/views/courses/show.html.erb
<div class="content-container">
  <div class="container-fluid"> 

    <div class="jumbotron">
      <h1 class="display-4">
        <%= @course.name %> 
      </h1>
      <p class="lead">
        <%= @course.description %> 
      </p>
      <br/>
      <%= link_to 'Edit', edit_course_path(@course), class:"btn btn-primary" %> 
      <%= link_to 'Back', courses_path, class:"btn btn-primary" %>
      <%= link_to 'Add Resources', new_resource_path, class:"btn btn-primary" %> 
    </div>

    <div class="card-body">
      <p>
        <strong>Description:</strong>
        <%= @course.description %>
      </p>

      <p><strong>Resources:</strong>
        <div class="tab">
          <% @all_resources.each do |res| %>
            <li>
              <%= link_to '', :onclick => "get_metadata('#{res.url}')" do %>
                <%= res.name %><br  />
              <% end %>
            </li>
          <% end %>
        </div>
        </p>
    </div>

  </div>
</div>


<script type="text/javascript">
  function get_metadata(url){
    $.get( url + "/metadata", function( data ){
      get_file(data.filename,data.mimetype,data.isWriteable,data.size,url);
    });
  }

  function get_file(filename, mimetype, isWriteable, size, url){
    filepicker.setKey("AEgoy56fEQziKJ8ajM2Luz");
    var blob = {
      url: url,
      filename: filename,
      mimetype: mimetype,
      isWriteable: isWriteable,
      size: size
    };  

    filepicker.exportFile(
      blob,
      function(Blob){
        console.log(Blob.url);
      }
    );
  }
</script>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-primary">
  <div class="container-fluid">
    <%= link_to 'Learning Management System', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarCollapse">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
              <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
          <li class="nav-item">
              <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
              <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
          </li>
          <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/_sidebar.html.erb
<div class="sidebar-container">
  <div class="footer-copyright text-center py-3">Logged in as: <br/> <%= current_user.email %></div>
  <ul class="sidebar-navigation">
    <li class="header">Navigation</li>
    <li>
      <%= link_to ' Homepage', root_path, class:"fa fa-home" %>
    </li>
    <li>
      <%= link_to ' Dashboard', home_about_path, class:"fa fa-tachometer" %>
    </li>
    <% if current_user.admin != false%> 
      <li class="header">Admin Panel</li>
      <li>
        <%= link_to ' Add User Manually', users_adding_adding_manually_path, class:"fa fa-user-plus" %>
      </li>
      <li>
        <%= link_to ' Add User From File', users_adding_adding_csv_path, class:"fa fa-user-plus" %> 
      </li>
    <% end %>
    <% if current_user.admin != false or current_user.teacher!= false %>
      <li>
        <%= link_to ' Show Users', home_show_users_path, class:"fa fa-bars" %> 
      </li>
    <% end %>
      <li>
        <%= link_to ' Show Courses', courses_path, class:"fa fa-book" %> 
      </li>
      <li>
        <%= link_to ' Upload Essay', new_essay_solution_path, class:"fa fa-upload" %> 
      </li>
    
  </ul>
</div>

app/views/home/about.html.erb
<div class="content-container">
    <div class="container-fluid"> 

        <h1>Dashboard</h1>

    </div>
</div>

app/views/home/index.html.erb
<div class="content-container">
    <div class="container-fluid">

        <h1>Home</h1>
        <h4> Welcome to Learning Management System!</h4>        
    </div>
</div>

app/views/home/show_users.html.erb
<div class="content-container">
    <div class="container-fluid">
    <h1>All Users</h1>
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead class="table-dark">
                    <tr>
                        <th>ID</th>
                        <th>First name</th>
                        <th>Last name</th>
                        <th>Email</th>
                        <th>Admin</th>
                        <th>Teacher</th>
                        <th>Student</th>
                    </tr>
                </thead>

                <tbody>
                    <% @users.each do |user| %>
                    <% if user.school == current_user.school %>
                    <tr>
                        <td><%= user.id %></td>
                        <td><%= user.first_name %></td>
                        <td><%= user.last_name %></td>
                        <td><%= user.email %></td>
                        <td><%= user.admin %></td>
                        <td><%= user.teacher %></td>
                        <td><%= user.student %></td>
                    </tr>
                    <% end %>
                    <% end %>
                </tbody>
            </table>

            <%= link_to 'Add User', users_adding_adding_manually_path, class:"btn btn-primary" %>
            <%= link_to 'Add Users From CSV', users_adding_adding_csv_path, class:"btn btn-primary" %>
        </div>
    </div>
</div>